spring:
  profiles:
    active: 
      - dev
---
server:
  port: 7001   #注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: dev
  application:
    name: springcloud-cloud-eureka-client

eureka:
  instance:
    hostname: eureka7001.com    #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，不通过eureka获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 7001   #注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: springcloud-cloud-eureka-client

eureka:
  instance:
    hostname: eureka7001.com    #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，不通过eureka获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/